server:
  port: 8084

spring:
  application:
    name: spring-cloud-api-gateway
  cloud:
    gateway:
      routes:
        - id: TRIP-SERVICE
          uri: lb://TRIP-SERVICE
          predicates:
            - Path= /trips/**

        - id: CUSTOM-TRIP-SERVICE
          uri: lb://CUSTOM-TRIP-SERVICE
          predicates:
            - Path= /custom-trip/**
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka