#spring:
#  security:
#    user:
#      name: root
#      password: root

spring:
  application:
    name: spring-security-demo
  datasource:
    driver: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3307/security-test?createDatabaseIfNotExist=true
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect