#spring:
#  security:
#    user:
#      name: root
#      password: root

spring:
  application:
    name: spring-security-demo
  datasource:
    driver: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security-test
    username: root
    password: 12345678

  jpa:
    hibernate:
      ddl-update: auto
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect